name: Release

permissions:
  contents: write

env:
  SBOM_NAME: "${{ github.event.repository.name }}-sbom.spdx.json"
  GPG_FINGERPRINT: B3596D99AED95A4831F8E9A1092017BA1C395379

on:
  push:
    tags:
      - 'v*'  # Triggers on any version tag

jobs:
  release:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT_OLD: ${{ env.GPG_FINGERPRINT }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        with:
          args: release --skip=docker,homebrew --rm-dist

      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          path: "./dist"
          output-file: ${{ env.SBOM_NAME }}
          format: "spdx"

      - name: Scan SBOM
        uses: anchore/scan-action@v6
        with:
          sbom: ${{ env.SBOM_NAME }}

      - name: Upload SBOM to Release
        run: gh release upload ${{ github.ref_name }} ${{ env.SBOM_NAME }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}